
# =======================================================
# FONT SETTINGS
# =======================================================
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 11.0

# =======================================================
# WINDOW SETTINGS
# =======================================================
# window header
hide_window_decorations yes

background_opacity 1

# --- Tab Bar Design ---
tab_bar_edge top
tab_bar_style separator
tab_separator ""
tab_bar_margin_width 10
tab_bar_margin_height 5 0

# Format: top right bottom left
window_padding_width 2 0 0 0

# =======================================================
# TABS DESIGN
# =======================================================

# --- Colors ---
active_tab_font_style   bold
inactive_tab_font_style normal

# --- Split Bubble Templates ---

# Active: White Circle (Index) -> Green Bubble (Title)
active_tab_title_template "{fmt.fg._c0caf5}{fmt.bg.default}{fmt.fg._1e1e2e}{fmt.bg._c0caf5} {index} {fmt.fg._c0caf5}{fmt.bg._9ece6a}{fmt.fg._1e1e2e}{fmt.bg._9ece6a} {title} {fmt.fg._9ece6a}{fmt.bg.default} "

# Inactive: White Circle (Index) -> Blue Bubble (Title)
tab_title_template        "{fmt.fg._c0caf5}{fmt.bg.default}{fmt.fg._1e1e2e}{fmt.bg._c0caf5} {index} {fmt.fg._c0caf5}{fmt.bg._7aa2f7}{fmt.fg._1e1e2e}{fmt.bg._7aa2f7} {title} {fmt.fg._7aa2f7}{fmt.bg.default} "

# Split screen layouts
enabled_layouts tall:bias=60;full_size=1;mirrored=false,grid,fat,splits,vertical,stack

# =======================================================
# THEME
# =======================================================
include ~/.config/kitty/tokyonight-theme.conf

# =======================================================
# STARTUP SEASION
# =======================================================
startup_session ~/.config/kitty/startup.session
