[mgr]
show_hidden = true
ratio = [1, 2, 5]   # panes size ratio

# show git status for files
[[plugin.prepend_fetchers]]
id  = "git"
url = "*"
group = "normal"
run = "git"

# show git status for directories
[[plugin.prepend_fetchers]]
id  = "git"
url = "*/"
group = "normal"
run = "git"

