"$schema" = 'https://starship.rs/config-schema.json'

palette = "tokyo_night"

# ── Layout ────────────────────────────────────────────────────────────────────
format = """
[](cap)\
$os$hostname\
[](fg:cap bg:dblue)\
$directory\
[](fg:dblue bg:navy)\
$git_branch$git_status\
[](fg:navy bg:dark)\
$jobs$status$cmd_duration\
[](fg:dark bg:darker)\
$time\
[](fg:darker)\
\n$character"""

# ── Colors ────────────────────────────────────────────────────────────────────
[palettes.tokyo_night]
cap    = "#a3aed2"
blue   = "#769ff0"
dblue  = "#474f76"
navy   = "#394260"
dark   = "#2a3346"
darker = "#20283b"

black  = "#090c0c"
white  = "#e3e5e5"
muted  = "#a0a9cb"
dim    = "#a9b1d6"

green  = "#9ece6a"
red    = "#f7768e"
gold   = "#e0af68"

# ── Config ───────────────────────────────────────────────────────────────────

[os]
disabled = false
style    = "bg:cap fg:black"
format   = "[$symbol]($style)"

[hostname]
ssh_only = true
style    = "bg:cap fg:black"
format   = '[@$hostname]($style)'

[directory]
style                     = "fg:white bg:dblue"
format                    = "[ $path ]($style)"
truncation_length         = 5
truncation_symbol         = "…/"
fish_style_pwd_dir_length = 2
truncate_to_repo          = false
read_only                 = " 󰌾 "
read_only_style           = "fg:red"
before_repo_root_style    = "fg:dim bg:blue"

[git_branch]
symbol            = "󰘬"
style             = "fg:blue bg:navy"
format            = '[ $symbol $branch ]($style)'
truncation_length = 30
truncation_symbol = "…"

[git_state]
disabled = false
style    = "bg:navy"
format   = '[\($state( $progress_current/$progress_total)\)]($style)'

[git_status]
style      = "bg:navy"
format     = '[$conflicted](fg:red bg:navy)[$deleted](fg:red bg:navy)[$renamed$modified$untracked](fg:gold bg:navy)[$staged](fg:green bg:navy)[$stashed](fg:muted bg:navy)[$ahead_behind](fg:blue bg:navy)'
stashed    = " "
conflicted = " "
ahead      = " ${count}"
behind     = " ${count}"
diverged   = "  ${ahead_count} ${behind_count}"
untracked  = " "
modified   = " "
staged     = " "
renamed    = " "
deleted    = " "

[jobs]
symbol           = "󰑮 "
style            = "fg:gold bg:dark"
format           = '[ $symbol$number ]($style)'
number_threshold = 2
symbol_threshold = 1

[status]
disabled              = false
symbol                = " 󰅙 "
not_executable_symbol = " 󱎘 "
not_found_symbol      = " 󰍉 "
sigint_symbol         = " 󰗼 "
signal_symbol         = " 󱐋 "
map_symbol            = true
style                 = "fg:red bg:dark"
format                = '[$symbol$common_meaning$signal_name$maybe_int ]($style)'

[cmd_duration]
min_time = 2000
style    = "fg:gold bg:dark"
format   = '[ 󱎫 $duration ]($style)'

[time]
disabled    = false
time_format = "%R"
style       = "fg:muted bg:darker"
format      = '[ 󱑒 $time ]($style)'

[character]
success_symbol = "[❯](bold green)"
error_symbol   = "[❯](bold red)"

[fill]
symbol = ""

# ── Constants ─────────────────────────────────────────────────────────────────
[os.symbols]
Alpaquita         = " "
Alpine            = " "
AlmaLinux         = " "
Amazon            = " "
Android           = " "
Arch              = " "
Artix             = " "
CentOS            = " "
CachyOS           = " "
Debian            = " "
DragonFly         = " "
Emscripten        = " "
EndeavourOS       = " "
Fedora            = " "
FreeBSD           = " "
Garuda            = "󰛓 "
Gentoo            = " "
HardenedBSD       = "󰞌 "
Illumos           = "󰈸 "
Kali              = " "
Linux             = " "
Mabox             = " "
Macos             = " "
Manjaro           = " "
Mariner           = " "
MidnightBSD       = " "
Mint              = "󰣭 "
NetBSD            = " "
NixOS             = " "
OpenBSD           = "󰈺 "
openSUSE          = " "
OracleLinux       = "󰌷 "
Pop               = " "
Raspbian          = " "
Redhat            = " "
RedHatEnterprise  = " "
RockyLinux        = " "
Redox             = "󰀘 "
Solus             = " "
SUSE              = " "
Ubuntu            = " "
Unknown           = " "
Void              = " "
Windows           = "󰍲 "

[directory.substitutions]
"Desktop"   = " "
"Documents" = "󰈙 "
"Downloads" = "󰇚 "
"Music"     = "󰝚 "
"Pictures"  = "󰙅 "
"Projects"  = "󰲋 "
"Public"    = " "
"Templates" = "󰏆 "
"Videos"    = " "
